//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Backend.Models", "FK_Historico_Amigos_IdAmigo", "Amigos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Backend.Models.Amigo), "Cache", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Backend.Models.Cache), true)]
[assembly: EdmRelationshipAttribute("Backend.Models", "FK_Historico_Amigos_IdDestino", "Amigos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Backend.Models.Amigo), "Cache", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Backend.Models.Cache), true)]
[assembly: EdmRelationshipAttribute("Backend.Models", "FK_Log_Cache_IdCache", "Cache", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Backend.Models.Cache), "Log", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Backend.Models.Log), true)]

#endregion

namespace Backend.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DadosAmigos : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DadosAmigos object using the connection string found in the 'DadosAmigos' section of the application configuration file.
        /// </summary>
        public DadosAmigos() : base("name=DadosAmigos", "DadosAmigos")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DadosAmigos object.
        /// </summary>
        public DadosAmigos(string connectionString) : base(connectionString, "DadosAmigos")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DadosAmigos object.
        /// </summary>
        public DadosAmigos(EntityConnection connection) : base(connection, "DadosAmigos")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Amigo> Amigos
        {
            get
            {
                if ((_Amigos == null))
                {
                    _Amigos = base.CreateObjectSet<Amigo>("Amigos");
                }
                return _Amigos;
            }
        }
        private ObjectSet<Amigo> _Amigos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cache> Caches
        {
            get
            {
                if ((_Caches == null))
                {
                    _Caches = base.CreateObjectSet<Cache>("Caches");
                }
                return _Caches;
            }
        }
        private ObjectSet<Cache> _Caches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Log> Logs
        {
            get
            {
                if ((_Logs == null))
                {
                    _Logs = base.CreateObjectSet<Log>("Logs");
                }
                return _Logs;
            }
        }
        private ObjectSet<Log> _Logs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Amigos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAmigos(Amigo amigo)
        {
            base.AddObject("Amigos", amigo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Caches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCaches(Cache cache)
        {
            base.AddObject("Caches", cache);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Logs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogs(Log log)
        {
            base.AddObject("Logs", log);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Backend.Models", Name="Amigo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Amigo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Amigo object.
        /// </summary>
        /// <param name="idAmigo">Initial value of the IdAmigo property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="local">Initial value of the Local property.</param>
        /// <param name="latitude">Initial value of the Latitude property.</param>
        /// <param name="longitude">Initial value of the Longitude property.</param>
        public static Amigo CreateAmigo(global::System.Int32 idAmigo, global::System.String nome, global::System.String local, global::System.Decimal latitude, global::System.Decimal longitude)
        {
            Amigo amigo = new Amigo();
            amigo.IdAmigo = idAmigo;
            amigo.Nome = nome;
            amigo.Local = local;
            amigo.Latitude = latitude;
            amigo.Longitude = longitude;
            return amigo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdAmigo
        {
            get
            {
                return _IdAmigo;
            }
            set
            {
                if (_IdAmigo != value)
                {
                    OnIdAmigoChanging(value);
                    ReportPropertyChanging("IdAmigo");
                    _IdAmigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdAmigo");
                    OnIdAmigoChanged();
                }
            }
        }
        private global::System.Int32 _IdAmigo;
        partial void OnIdAmigoChanging(global::System.Int32 value);
        partial void OnIdAmigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Local
        {
            get
            {
                return _Local;
            }
            set
            {
                OnLocalChanging(value);
                ReportPropertyChanging("Local");
                _Local = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Local");
                OnLocalChanged();
            }
        }
        private global::System.String _Local;
        partial void OnLocalChanging(global::System.String value);
        partial void OnLocalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.Decimal _Latitude;
        partial void OnLatitudeChanging(global::System.Decimal value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.Decimal _Longitude;
        partial void OnLongitudeChanging(global::System.Decimal value);
        partial void OnLongitudeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
//        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Backend.Models", "FK_Historico_Amigos_IdAmigo", "Cache")]
        public EntityCollection<Cache> Amigos
        {
            internal get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cache>("Backend.Models.FK_Historico_Amigos_IdAmigo", "Cache");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cache>("Backend.Models.FK_Historico_Amigos_IdAmigo", "Cache", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
//        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Backend.Models", "FK_Historico_Amigos_IdDestino", "Cache")]
        public EntityCollection<Cache> Destinos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cache>("Backend.Models.FK_Historico_Amigos_IdDestino", "Cache");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cache>("Backend.Models.FK_Historico_Amigos_IdDestino", "Cache", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Backend.Models", Name="Cache")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cache : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cache object.
        /// </summary>
        /// <param name="idCache">Initial value of the IdCache property.</param>
        /// <param name="idAmigo">Initial value of the IdAmigo property.</param>
        /// <param name="idDestino">Initial value of the IdDestino property.</param>
        /// <param name="distancia">Initial value of the Distancia property.</param>
        public static Cache CreateCache(global::System.Int64 idCache, global::System.Int32 idAmigo, global::System.Int32 idDestino, global::System.Decimal distancia)
        {
            Cache cache = new Cache();
            cache.IdCache = idCache;
            cache.IdAmigo = idAmigo;
            cache.IdDestino = idDestino;
            cache.Distancia = distancia;
            return cache;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IdCache
        {
            get
            {
                return _IdCache;
            }
            set
            {
                if (_IdCache != value)
                {
                    OnIdCacheChanging(value);
                    ReportPropertyChanging("IdCache");
                    _IdCache = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCache");
                    OnIdCacheChanged();
                }
            }
        }
        private global::System.Int64 _IdCache;
        partial void OnIdCacheChanging(global::System.Int64 value);
        partial void OnIdCacheChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdAmigo
        {
            get
            {
                return _IdAmigo;
            }
            set
            {
                OnIdAmigoChanging(value);
                ReportPropertyChanging("IdAmigo");
                _IdAmigo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdAmigo");
                OnIdAmigoChanged();
            }
        }
        private global::System.Int32 _IdAmigo;
        partial void OnIdAmigoChanging(global::System.Int32 value);
        partial void OnIdAmigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdDestino
        {
            get
            {
                return _IdDestino;
            }
            set
            {
                OnIdDestinoChanging(value);
                ReportPropertyChanging("IdDestino");
                _IdDestino = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdDestino");
                OnIdDestinoChanged();
            }
        }
        private global::System.Int32 _IdDestino;
        partial void OnIdDestinoChanging(global::System.Int32 value);
        partial void OnIdDestinoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Distancia
        {
            get
            {
                return _Distancia;
            }
            set
            {
                OnDistanciaChanging(value);
                ReportPropertyChanging("Distancia");
                _Distancia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Distancia");
                OnDistanciaChanged();
            }
        }
        private global::System.Decimal _Distancia;
        partial void OnDistanciaChanging(global::System.Decimal value);
        partial void OnDistanciaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Backend.Models", "FK_Historico_Amigos_IdAmigo", "Amigos")]
        public Amigo Amigo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Amigo>("Backend.Models.FK_Historico_Amigos_IdAmigo", "Amigos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Amigo>("Backend.Models.FK_Historico_Amigos_IdAmigo", "Amigos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Amigo> AmigoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Amigo>("Backend.Models.FK_Historico_Amigos_IdAmigo", "Amigos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Amigo>("Backend.Models.FK_Historico_Amigos_IdAmigo", "Amigos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Backend.Models", "FK_Historico_Amigos_IdDestino", "Amigos")]
        public Amigo Destino
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Amigo>("Backend.Models.FK_Historico_Amigos_IdDestino", "Amigos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Amigo>("Backend.Models.FK_Historico_Amigos_IdDestino", "Amigos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Amigo> DestinoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Amigo>("Backend.Models.FK_Historico_Amigos_IdDestino", "Amigos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Amigo>("Backend.Models.FK_Historico_Amigos_IdDestino", "Amigos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Backend.Models", "FK_Log_Cache_IdCache", "Log")]
        public Log Log
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Log>("Backend.Models.FK_Log_Cache_IdCache", "Log").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Log>("Backend.Models.FK_Log_Cache_IdCache", "Log").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Log> LogReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Log>("Backend.Models.FK_Log_Cache_IdCache", "Log");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Log>("Backend.Models.FK_Log_Cache_IdCache", "Log", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Backend.Models", Name="Log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Log object.
        /// </summary>
        /// <param name="idCache">Initial value of the IdCache property.</param>
        /// <param name="radianosLatitudeOrigem">Initial value of the RadianosLatitudeOrigem property.</param>
        /// <param name="radianosLatitudeDestino">Initial value of the RadianosLatitudeDestino property.</param>
        /// <param name="radianosThetaLongitude">Initial value of the RadianosThetaLongitude property.</param>
        /// <param name="seno">Initial value of the Seno property.</param>
        /// <param name="coseno">Initial value of the Coseno property.</param>
        /// <param name="angulo">Initial value of the Angulo property.</param>
        /// <param name="milhas">Initial value of the Milhas property.</param>
        /// <param name="kilometros">Initial value of the Kilometros property.</param>
        public static Log CreateLog(global::System.Int64 idCache, global::System.Decimal radianosLatitudeOrigem, global::System.Decimal radianosLatitudeDestino, global::System.Decimal radianosThetaLongitude, global::System.Decimal seno, global::System.Decimal coseno, global::System.Decimal angulo, global::System.Decimal milhas, global::System.Decimal kilometros)
        {
            Log log = new Log();
            log.IdCache = idCache;
            log.RadianosLatitudeOrigem = radianosLatitudeOrigem;
            log.RadianosLatitudeDestino = radianosLatitudeDestino;
            log.RadianosThetaLongitude = radianosThetaLongitude;
            log.Seno = seno;
            log.Coseno = coseno;
            log.Angulo = angulo;
            log.Milhas = milhas;
            log.Kilometros = kilometros;
            return log;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IdCache
        {
            get
            {
                return _IdCache;
            }
            set
            {
                if (_IdCache != value)
                {
                    OnIdCacheChanging(value);
                    ReportPropertyChanging("IdCache");
                    _IdCache = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCache");
                    OnIdCacheChanged();
                }
            }
        }
        private global::System.Int64 _IdCache;
        partial void OnIdCacheChanging(global::System.Int64 value);
        partial void OnIdCacheChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal RadianosLatitudeOrigem
        {
            get
            {
                return _RadianosLatitudeOrigem;
            }
            set
            {
                OnRadianosLatitudeOrigemChanging(value);
                ReportPropertyChanging("RadianosLatitudeOrigem");
                _RadianosLatitudeOrigem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RadianosLatitudeOrigem");
                OnRadianosLatitudeOrigemChanged();
            }
        }
        private global::System.Decimal _RadianosLatitudeOrigem;
        partial void OnRadianosLatitudeOrigemChanging(global::System.Decimal value);
        partial void OnRadianosLatitudeOrigemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal RadianosLatitudeDestino
        {
            get
            {
                return _RadianosLatitudeDestino;
            }
            set
            {
                OnRadianosLatitudeDestinoChanging(value);
                ReportPropertyChanging("RadianosLatitudeDestino");
                _RadianosLatitudeDestino = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RadianosLatitudeDestino");
                OnRadianosLatitudeDestinoChanged();
            }
        }
        private global::System.Decimal _RadianosLatitudeDestino;
        partial void OnRadianosLatitudeDestinoChanging(global::System.Decimal value);
        partial void OnRadianosLatitudeDestinoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal RadianosThetaLongitude
        {
            get
            {
                return _RadianosThetaLongitude;
            }
            set
            {
                OnRadianosThetaLongitudeChanging(value);
                ReportPropertyChanging("RadianosThetaLongitude");
                _RadianosThetaLongitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RadianosThetaLongitude");
                OnRadianosThetaLongitudeChanged();
            }
        }
        private global::System.Decimal _RadianosThetaLongitude;
        partial void OnRadianosThetaLongitudeChanging(global::System.Decimal value);
        partial void OnRadianosThetaLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Seno
        {
            get
            {
                return _Seno;
            }
            set
            {
                OnSenoChanging(value);
                ReportPropertyChanging("Seno");
                _Seno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Seno");
                OnSenoChanged();
            }
        }
        private global::System.Decimal _Seno;
        partial void OnSenoChanging(global::System.Decimal value);
        partial void OnSenoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Coseno
        {
            get
            {
                return _Coseno;
            }
            set
            {
                OnCosenoChanging(value);
                ReportPropertyChanging("Coseno");
                _Coseno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Coseno");
                OnCosenoChanged();
            }
        }
        private global::System.Decimal _Coseno;
        partial void OnCosenoChanging(global::System.Decimal value);
        partial void OnCosenoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Angulo
        {
            get
            {
                return _Angulo;
            }
            set
            {
                OnAnguloChanging(value);
                ReportPropertyChanging("Angulo");
                _Angulo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Angulo");
                OnAnguloChanged();
            }
        }
        private global::System.Decimal _Angulo;
        partial void OnAnguloChanging(global::System.Decimal value);
        partial void OnAnguloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Milhas
        {
            get
            {
                return _Milhas;
            }
            set
            {
                OnMilhasChanging(value);
                ReportPropertyChanging("Milhas");
                _Milhas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Milhas");
                OnMilhasChanged();
            }
        }
        private global::System.Decimal _Milhas;
        partial void OnMilhasChanging(global::System.Decimal value);
        partial void OnMilhasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Kilometros
        {
            get
            {
                return _Kilometros;
            }
            set
            {
                OnKilometrosChanging(value);
                ReportPropertyChanging("Kilometros");
                _Kilometros = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Kilometros");
                OnKilometrosChanged();
            }
        }
        private global::System.Decimal _Kilometros;
        partial void OnKilometrosChanging(global::System.Decimal value);
        partial void OnKilometrosChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Backend.Models", "FK_Log_Cache_IdCache", "Cache")]
        public Cache Cache
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cache>("Backend.Models.FK_Log_Cache_IdCache", "Cache").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cache>("Backend.Models.FK_Log_Cache_IdCache", "Cache").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cache> CacheReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cache>("Backend.Models.FK_Log_Cache_IdCache", "Cache");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cache>("Backend.Models.FK_Log_Cache_IdCache", "Cache", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
